# Generated by Django 4.0.6 on 2024-04-05 17:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_name', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('kadet_id', models.CharField(blank=True, max_length=80, null=True)),
                ('bug_type', models.CharField(blank=True, choices=[('Bug', 'Bug'), ('BugTesting', 'BugTesting'), ('UserStory', 'UserStory'), ('UserStoryTesting', 'UserStoryTesting')], max_length=100, null=True)),
                ('bug_title', models.CharField(blank=True, max_length=800, null=True)),
                ('status', models.CharField(blank=True, choices=[('NOTSTARTED', 'NOT-STARTED'), ('INPROGRESS', 'IN-PROGRESS'), ('FIXED', 'FIXED'), ('HOLD', 'HOLD')], max_length=100, null=True)),
                ('priority', models.CharField(blank=True, choices=[('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], max_length=10, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('assgined_to', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Name')),
                ('board_obj', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='bug.board', verbose_name='Board Name')),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_name', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_result', models.CharField(blank=True, max_length=80, null=True)),
                ('bug_obj', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='bug.bug', verbose_name='Bug Name')),
            ],
        ),
    ]
