# Generated by Django 4.0.6 on 2024-04-10 09:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='remark',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='bug',
            old_name='date',
            new_name='end_date',
        ),
        migrations.RemoveField(
            model_name='bug',
            name='status',
        ),
        migrations.AddField(
            model_name='bug',
            name='board_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='bug',
            name='bug_level',
            field=models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Normal', 'Normal'), ('Moderate', 'Moderate'), ('Difficult', 'Difficult')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bug',
            name='dev_status',
            field=models.CharField(blank=True, choices=[('NOTSTARTED', 'NOT-STARTED'), ('INPROGRESS', 'IN-PROGRESS'), ('FIXED', 'FIXED'), ('HOLD', 'HOLD'), ('OPEN', 'OPEN'), ('REOPEN', 'REOPEN'), ('CLOSE', 'CLOSE')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bug',
            name='record_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='bug',
            name='release_det',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='bug.releasedetails', verbose_name='Release Name'),
        ),
        migrations.AddField(
            model_name='bug',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='bug',
            name='testing_status',
            field=models.CharField(blank=True, choices=[('NOTSTARTED', 'NOT-STARTED'), ('INPROGRESS', 'IN-PROGRESS'), ('FIXED', 'FIXED'), ('HOLD', 'HOLD'), ('OPEN', 'OPEN'), ('REOPEN', 'REOPEN'), ('CLOSE', 'CLOSE')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='rel_det_obj',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='bug.releasedetails', verbose_name='Release Object'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='test_case_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='test_result',
            field=models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('Retested', 'Retested'), ('NotRetested', 'NotRetested')], max_length=80, null=True),
        ),
    ]
