# Generated by Django 4.0.6 on 2024-04-10 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0003_testcase_action_testcase_actual_result_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_count', models.CharField(blank=True, max_length=80, null=True)),
                ('description', models.CharField(blank=True, max_length=800, null=True)),
                ('action', models.CharField(blank=True, max_length=800, null=True)),
                ('expected_result', models.CharField(blank=True, max_length=800, null=True)),
                ('actual_result', models.CharField(blank=True, max_length=800, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='action',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='actual_result',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='description',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='expected_result',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='step',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='test_case_id',
        ),
        migrations.CreateModel(
            name='TestCaseSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_case_name', models.CharField(blank=True, max_length=80, null=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('step_obj', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='bug.steps', verbose_name='Step')),
            ],
        ),
        migrations.AddField(
            model_name='testcase',
            name='test_case_obj',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='bug.testcasesteps', verbose_name='TestCase ID'),
        ),
    ]
