# Generated by Django 4.0.6 on 2024-04-10 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0004_steps_remove_testcase_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcasesteps',
            name='step_obj',
        ),
        migrations.AddField(
            model_name='steps',
            name='test_case_step_obj',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='bug.testcasesteps', verbose_name='TestCaseSteps'),
        ),
    ]
